#!/usr/bin/env ruby
EXAMPLES = './examples'
LOG = './tmp/error.log'

RUBY = 'ruby -W0 -I ./lib'

Dir.entries(EXAMPLES).each do |file|
  next unless file=~/^\w+\.rb$/
  file  = File.join EXAMPLES, file
  unless system("#{RUBY} #{file} 2> #{LOG}") and File.zero?(LOG)
    $stderr.puts "Error in #{file}.  See #{LOG}.".
    exit
  end
end
