#! ruby
require 'test/unit'
require 'gtk3app'
using Rafini::String

class TestConfig < Test::Unit::TestCase
  def test_config
    assert_equal Proc, Gtk3App::CONFIG.class
    assert_equal Hash, Gtk3App::CONFIG.to_h.class

    gopen = Gtk3App::CONFIG[:Open]
    assert_equal 'xdg-open', gopen
    assert system("which #{gopen}")

    cnf = Gtk3App::CONFIG.to_h
    # Checking that our bangs! are all there.
    ['main!',
     'stage!','toolbar!',
     'fs!','about!','help!','minime!','quit!',
     'app_menu!',
     'quit_ursure!','quit_exception!',
    ].each do |s|
      k = s.to_sym # :key!
      assert_not_nil cnf[k], k
      k = s.chop.to_sym # :key
      assert_not_nil cnf[k], k
      k = s.chop.upcase.to_sym # :KEY
      assert_not_nil cnf[k], k
    end

    # Checking convention use
    cnf.each do |k,v|
      case k
      when /^[A-Z_]+$/
        assert_equal Array, v.class
      when /^[a-z_]+$/
        assert_equal Hash, v.class
      when /^[a-zA-Z]+$/
        assert((v.class==String) || (v.class==Integer))
      when /^\w+\!$/
        assert_equal Array, v.class
      else
        raise "Got bad CONFIG key :#{k}."
      end
    end

    # sanity check
    assert_equal Gtk3App::VERSION.semantic(0..1), cnf[:about_dialog][:set_version]
  end
end
