#! ruby
require 'test/unit'
require 'gtk3app'

class TestUserSpace < Test::Unit::TestCase
  using Rafini::String
  # Presumably, the examples have be run.
  # Going to test the XDG files are as expected.
  def test_user_space
    data   = UserSpace::XDG['data'].to_s
    config = UserSpace::XDG['config'].to_s
    cache  = UserSpace::XDG['cache'].to_s

    assert File.exist?(data),   data
    assert File.exist?(config), config
    assert File.exist?(cache),  cache

    data   = File.join data,   'gtk3app'
    config = File.join config, 'gtk3app'
    cache  = File.join cache,  'gtk3app'

    assert File.exist?(data),   data
    assert File.exist?(config), config
    assert File.exist?(cache),  cache

    # Check config file
    configfilename = "config-#{Gtk3App::VERSION.semantic(0..1)}.rbon"
    file = File.join config, configfilename
    assert File.exist?(file), file
    # If anything changes the config file, want to know about it!
    assert_equal '665f1555c9ee858c683136881a312004',
      `md5sum '#{file}'`.strip.split(/\s+/).first

# TODO:
=begin
    [data,config,cache].each do |dir|
      # Note that SimpleApp does not trigger UserSpace
      ['intermediateapp','expertapp'].each do |x|
        xdir = File.join dir, x
        assert File.exist?(xdir), xdir
        case dir
        when data
          file = File.join xdir, 'VERSION'
          assert File.exist?(file), file
          assert_equal Gtk3App::VERSION, File.read(file).strip
        when config
          file = File.join xdir, configfilename
          assert File.exist?(file), file
          case x
          when 'intermediateapp'
            assert_equal 'd9a4f8de2f9a0f0e0f7ce97fb1271421',
              `md5sum '#{file}'`.strip.split(/\s+/).first
          when 'expertapp'
            assert_equal 'f38b9efd0306b2577017ae3abfbaa092',
              `md5sum '#{file}'`.strip.split(/\s+/).first
          end
        end
      end
    end
=end
  end
end
