#! ruby
require 'test/unit'
require 'gtk3app'

class TestUserSpace < Test::Unit::TestCase
  using Rafini::String
  # Presumably, the examples have be run.
  # Going to test the XDG files are as expected.
  def test_user_space
    data   = UserSpace::XDG['data']
    config = UserSpace::XDG['config']
    cache  = UserSpace::XDG['cache']

    assert File.exist?(data),   data
    assert File.exist?(config), config
    assert File.exist?(cache),  cache

    data   = File.join data,   'gtk3app'
    config = File.join config, 'gtk3app'
    cache  = File.join cache,  'gtk3app'

    assert File.exist?(data),   data
    assert File.exist?(config), config
    assert File.exist?(cache),  cache

    # Check config file
    configfilename = "config-#{Gtk3App::VERSION.semantic(0..1)}.rbon"
    file = File.join config, configfilename
    assert File.exist?(file), file
    # If anything changes the config file, want to know about it!
    assert_equal 'b6b40c3679eac8992ef9047701aeba30',
      `md5sum '#{file}'`.strip.split(/\s+/).first

    [data,config,cache].each do |dir|
      # Currently, only expert triggers xdg files:
      ['expert'].each do |x|
        xdir = File.join dir, x
        assert File.exist?(xdir), xdir
        case dir
        when data
          file = File.join xdir, 'logo.png'
          assert File.exist?(file), file
        when config
          # Examples should be be version "1.2.3"
          # Build changes should not alter config.
          file = File.join xdir, 'config-1.2.rbon'
          $stderr.puts file
          assert File.exist?(file), file
        end
      end
    end
  end
end
