#! ruby
require 'test/unit'
require 'gtk3app/version'

class TestVersion < Test::Unit::TestCase
  def test_version
    assert_nothing_raised() do
      version = '1.2.0'
      assert_equal version, Gtk3App::VERSION
      assert_equal version, File.read('./data/VERSION').strip
      # Ensure that everything that looks like version agrees
      `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' examples/*.* lib/**.* data/VERSION`.strip.split(/\n/).each do |line|
        assert_equal version, line.strip.split(/:/).last, line
      end
    end
  end
end
