#!/usr/bin/env ruby

if ARGV[0]
  raise "#{ARGV[0]} ???" unless system("which '#{ARGV[0]}' 2> /dev/null")
  RUBY = "#{ARGV[0]} -I ./lib"
else
  RUBY = 'ruby -I ./lib'
end

LOG = './test/errors.log'

def fn(name)
  "./test/tc_#{name}"
end

def tc(name)
  system "#{RUBY} #{fn(name)} > #{LOG}"
end

if tc('version')    and
   tc('config')     and
   tc('slot')       and
   tc('user_space')
  puts 'All tests passed!'
  File.unlink LOG
else
  puts "There were errors.  See #{LOG}"
  exit 1
end
